//SHOPPING CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

//Sección de FAVORITOS
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_ONE_FROM_FAVORITES = "REMOVE_ONE_FROM_FAVORITES"
export const REMOVE_ALL_FROM_FAVORITES = "REMOVE_ALL_FROM_FAVORITES"
export const CLEAR_FAVORITES = "CLEAR_FAVORITES"